default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: local
    hooks:
      - id: pymarkdownlnt
        name: PyMarkdown Lint
        entry: pymarkdownlnt scan
        language: system
        types: [markdown]

      - id: yamllint
        name: YAML Lint
        entry: yamllint
        language: system
        types: [yaml]
