version: '3.8'

services:
  api:
    build:
      context: ./api
      target: prod  # Cible l'étape de production dans votre Dockerfile
    image: europe-west9-docker.pkg.dev/sylvan-bonbon-496812-e6/images-docker/simplon-rag-api:latest

  frontend:
    build:
      context: ./frontend
      target: prod  # Cible l'étape de production dans votre Dockerfile
    image: europe-west9-docker.pkg.dev/sylvan-bonbon-496812-e6/images-docker/simplon-rag-frontend:latest
