name: CI/CD Production Deployment

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  # On crée deux variables pour nos deux images distinctes
  IMAGE_API: ghcr.io/${{ github.repository }}/api
  IMAGE_FRONT: ghcr.io/${{ github.repository }}/frontend

jobs:
  # 3. Étape de Build et Publication sur GHCR
  build-and-push:
    needs: [ test-api, test-frontend ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- BUILD DE L'API ---
      - name: Extract metadata for API
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/simplon-rag-api
          tags: |
            type=raw,value=latest

      - name: Build and push API Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}

      # --- BUILD DU FRONTEND ---
      - name: Extract metadata for Frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/simplon-rag-frontend
          tags: |
            type=raw,value=latest

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/app-ia
            # On force le VPS à récupérer les deux nouvelles images
            docker compose pull
            # On relance tout proprement
            docker compose up -d --remove-orphans
            docker image prune -f
