name: CI — Build, push et deploy

on:
  push:
    branches: ['feat/deploy-Image']

env:
  REGISTRY: ghcr.io

jobs:

  # ── Tests ──────────────────────────────────────────────────
  test:
    runs-on: ubuntu-latest
    env:
      MISTRAL_API_KEY: dummy-key-for-tests
      POSTGRES_PASSWORD: dummy-password
      POSTGRES_USER: rag_user
      POSTGRES_DB: rag
      POSTGRES_HOST: localhost
      POSTGRES_PORT: "5432"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer uv
        uses: astral-sh/setup-uv@v3

      - name: Installer les dépendances
        working-directory: ./api
        run: uv sync --frozen --extra dev

      - name: Lancer les tests unitaires
        working-directory: ./api
        run: uv run pytest tests/unit/ -v

  # ── Build et push API ──────────────────────────────────────
  build-and-push-api:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Connexion à GHCR
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extraire les métadonnées API
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/umbertoEmonds/vps_rag-api

      - name: Build et push API
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./api
          target: prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # ── Build et push Frontend ─────────────────────────────────
  build-and-push-frontend:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Connexion à GHCR
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extraire les métadonnées Frontend
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/umbertoEmonds/vps_rag-frontend

      - name: Build et push Frontend
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./frontend
          target: prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
